### ISSUE TITLE
How to remove blood splatter?

### ISSUE THREAD

**Issue by pesky-wobbit** [Vauryx/TargetReacts#1]
I see the setting to prevent it, but once the blood splatter is there I can't see how to remove it.
Love the module. Thx!

**Comment by Vauryx** [comment]
I will push an update soon that should give you a button to remove them, I
think an option to automatically remove them full-healed might also be good.
In the meantime, look for a macro called "deletefiltersonselected" or
something similar in your token magic macros. Running that with the token
selected will clear the blood effects.
Thanks for trying it out!

**Comment by Vauryx** [comment]
Added ability to remove blood from token through the use of a scene menu button. It's labeled "Heal Token". The label name may change lol
