### ISSUE TITLE
Feature Request: global delay for shakes, blood splatter, and sound

### ISSUE THREAD

**Issue by weepingminotaur** [Vauryx/TargetReacts#5]
In order to sync up with other modules (such as Automated Animations), it would be great to be able to delay all shakes, blood, and sound (in milliseconds) in module settings, so the effects happen after weapon or spell animations.

**Comment by Vauryx** [comment]
I will look into adding global delay options for the next update - thanks for trying out the module!

**Comment by Vauryx** [comment]
Closing this ticket as one is already open for this feature
